#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements. See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.
#

# build Apache Thrift on Travis CI - https://travis-ci.org/

sudo: required

services:
  - docker

install:
  # TODO: Once merged, remove experimental tag and use latest
  - docker pull thrift/$DISTRO:experiment || true
  - cp -r ./build/docker/scripts/*.sh ./build/docker/$DISTRO/scripts/
  - docker build -q -t thrift-build build/docker/$DISTRO

script:
  - docker run $DOCKER_ENV -v $(pwd):/thrift/src -it thrift-build $DOCKER_CMD $DOCKER_ARG

env:
  global:
    - TEST_NAME=""
    - DOCKER_CMD="none"
    - DOCKER_ARG=""
    - DOCKER_ENV="-e CC=clang -e CXX=clang++"
    - DISTRO=ubuntu

  matrix:
    # TODO: Break up by protocol types to avoid 50min limit
    - TEST_NAME="Cross Language Tests"
      DOCKER_CMD="../cross-test.sh"
      DOCKER_ARG="--enable-tutorial=no"
      DOCKER_ENV="-e CC=clang -e CXX=clang++ -e THRIFT_CROSSTEST_CONCURRENCY=4"

    # TODO: Remove them once migrated to CMake
    # Autotools builds
    - TEST_NAME="C C++ C# D Erlang Go Haxe (automake)"
      DOCKER_CMD="../autotools.sh"
      DOCKER_ARG="--without-dart --without-haskell --without-java --without-lua --without-nodejs --without-perl --without-php --without-php_extension --without-python --without-ruby"

    - TEST_NAME="C C++ - GCC (automake)"
      DOCKER_CMD="../autotools.sh"
      DOCKER_ARG="--without-csharp --without-java --without-erlang --without-nodejs --without-lua --without-python --without-perl --without-php --without-php_extension --without-dart --without-ruby --without-haskell --without-go --without-haxe --without-d"

    - TEST_NAME="Java Lua Perl PHP Python Ruby (automake)"
      DOCKER_CMD="../autotools.sh"
      DOCKER_ARG="--without-cpp --without-haskell --without-c_glib --without-csharp --without-d --without-dart --without-erlang --without-go --without-haxe"

    # Tutorial build is unstable
    - TEST_NAME="Dart (automake)"
      DOCKER_CMD="../autotools.sh"
      DOCKER_ARG="--without-cpp --without-haskell --without-c_glib --without-csharp --without-d --without-erlang --without-go --without-haxe --without-java --without-lua --without-nodejs --without-perl --without-php --without-php_extension --without-python --without-ruby --enable-tutorial=no"

    # These are flaky and also have lengthy output
    - TEST_NAME="Haskell Node.js (automake)"
      DOCKER_CMD="../autotools.sh"
      DOCKER_ARG="--without-cpp --without-c_glib --without-csharp --without-d --without-dart --without-erlang --without-go --without-haxe --without-java --without-lua --without-perl --without-php --without-php_extension --without-python --without-ruby"

    # CMake build
    - TEST_NAME="All"
      DOCKER_CMD="../cmake.sh"

    - TEST_NAME="C C++ - GCC"
      DOCKER_CMD="../cmake.sh"
      DOCKER_ARG="-DWITH_PYTHON=OFF -DWITH_JAVA=OFF -DWITH_HASKELL=OFF"
      DOCKER_ENV="-e CC=gcc -e CXX=g++"

    - TEST_NAME="C++ (Boost Thread)"
      DOCKER_CMD="../cmake.sh"
      DOCKER_ARG="-DWITH_BOOSTTHREADS=ON -DWITH_PYTHON=OFF -DWITH_C_GLIB=OFF -DWITH_JAVA=OFF -DWITH_HASKELL=OFF"

    - TEST_NAME="C++ (Boost Thread - GCC)"
      DOCKER_CMD="../cmake.sh"
      DOCKER_ARG="-DWITH_BOOSTTHREADS=ON -DWITH_PYTHON=OFF -DWITH_C_GLIB=OFF -DWITH_JAVA=OFF -DWITH_HASKELL=OFF"
      DOCKER_ENV="-e CC=gcc -e CXX=g++"

    - TEST_NAME="C++ (Std Thread)"
      DOCKER_CMD="../cmake.sh"
      DOCKER_ARG="-DWITH_STDTHREADS=ON -DCMAKE_CXX_FLAGS='-std=c++11' -DWITH_PYTHON=OFF -DWITH_C_GLIB=OFF -DWITH_JAVA=OFF -DWITH_HASKELL=OFF"

    - TEST_NAME="C++ (Std Thread - GCC)"
      DOCKER_CMD="../cmake.sh"
      DOCKER_ARG="-DWITH_STDTHREADS=ON -DCMAKE_CXX_FLAGS='-std=c++11' -DWITH_PYTHON=OFF -DWITH_C_GLIB=OFF -DWITH_JAVA=OFF -DWITH_HASKELL=OFF"
      DOCKER_ENV="-e CC=gcc -e CXX=g++"

    - TEST_NAME="Compiler (mingw)"
      DOCKER_CMD="../cmake.sh"
      DOCKER_ARG="-DCMAKE_TOOLCHAIN_FILE=../build/cmake/mingw32-toolchain.cmake -DBUILD_COMPILER=ON -DBUILD_LIBRARIES=OFF -DBUILD_TESTING=OFF -DBUILD_EXAMPLES=OFF"
      DOCKER_ENV=""

    - TEST_NAME="All (CentOS)"
      DOCKER_CMD="../cmake.sh"
      DISTRO=centos

    - TEST_NAME="C C++ - GCC (CentOS)"
      DOCKER_CMD="../cmake.sh"
      DOCKER_ARG="-DWITH_PYTHON=OFF -DWITH_JAVA=OFF -DWITH_HASKELL=OFF"
      DOCKER_ENV="-e CC=gcc -e CXX=g++"
      DISTRO=centos

    # Distribution
    - TEST_NAME="make dist"
      DOCKER_CMD="../make-dist.sh"
      DOCKER_ENV="-e CC=gcc -e CXX=g++"

    - TEST_NAME="Debian Packages"
      DOCKER_CMD="../dpkg.sh"
      DOCKER_ENV="-e CC=gcc -e CXX=g++"

matrix:
  allow_failures:
    - env: TEST_NAME="All (CentOS)" DOCKER_CMD="../cmake.sh" DISTRO=centos
    - env: TEST_NAME="C C++ - GCC (CentOS)" DOCKER_CMD="../cmake.sh" DOCKER_ARG="-DWITH_PYTHON=OFF -DWITH_JAVA=OFF -DWITH_HASKELL=OFF" DOCKER_ENV="-e CC=gcc -e CXX=g++" DISTRO=centos

  include:
    # QA jobs for code analytics and metrics
    #
    # static code analysis with cppcheck
    # add --error-exitcode=1 to --enable=all as soon as everything is fixed
    - env: TEST_NAME="cppcheck"
      install:
        - sudo apt-get update
        - sudo apt-get install cppcheck
      script:
        # Compiler cppcheck (All)
        - cppcheck --force --quiet --inline-suppr --enable=all -j2 compiler/cpp/src
        # C++ cppcheck (All)
        - cppcheck --force --quiet --inline-suppr --enable=all -j2 lib/cpp/src lib/cpp/test test/cpp tutorial/cpp
        # C Glib cppcheck (All)
        - cppcheck --force --quiet --inline-suppr --enable=all -j2 lib/c_glib/src lib/c_glib/test test/c_glib/src tutorial/c_glib
        # Silent error checks
        - cppcheck --force --quiet --inline-suppr --error-exitcode=1 -j2 compiler/cpp/src
        - cppcheck --force --quiet --inline-suppr --error-exitcode=1 -j2 lib/cpp/src lib/cpp/test test/cpp tutorial/cpp
        - cppcheck --force --quiet --inline-suppr --error-exitcode=1 -j2 lib/c_glib/src lib/c_glib/test test/c_glib/src tutorial/c_glib

    # search for TODO etc within source tree
    # some statistics about the code base
    # some info about the build machine
    - env:    TEST_NAME="TODO FIXME HACK, LoC and system info"
      install:
        - sudo apt-get update
        - sudo apt-get install sloccount
      script:
        - grep -r TODO *
        - grep -r FIXME *
        - grep -r HACK *
        # LoC
        - sloccount .
        # System Info
        - dpkg -l
        - uname -a
